# Generated by Django 6.0.3 on 2026-03-09 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField()),
                ('risk_category', models.CharField(choices=[('Low', 'Low Risk'), ('Moderate', 'Moderate Risk'), ('High', 'High Risk')], max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('shap_values', models.JSONField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='patients.patient')),
            ],
        ),
    ]
