# Generated by Django 4.2.10 on 2026-04-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_modelmetric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelmetric',
            options={},
        ),
        migrations.AddField(
            model_name='modelmetric',
            name='model_name',
            field=models.CharField(default='XGBoost', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='accuracy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='auc_roc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='f1_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='global_importance',
            field=models.JSONField(help_text='Global SHAP values'),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='precision',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='recall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetric',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
    ]
