# Generated by Django 6.0.3 on 2026-03-09 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bacilloscopy_Sputum', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (4, 'Not Applicable'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Sputum_2', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (4, 'Not Applicable'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Other', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (4, 'Not Applicable'), (9, 'Ignored')], null=True)),
                ('Sputum_Culture', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'In Progress'), (4, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Rifampicin', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Isoniazid', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Ethambutol', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Streptomycin', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Pyrazinamide', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Ethionamide', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Other_Drugs', models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Resistant'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Supervised_Treatment', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_1', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_2', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_3', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_4', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_5', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Bacilloscopy_Month_6', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Outcome_Status', models.IntegerField(blank=True, choices=[(1, 'Cure'), (2, 'Abandonment'), (3, 'Death by TB'), (4, 'Death Other'), (5, 'Transfer'), (6, 'Diagnosis Changed'), (7, 'MDR-TB'), (8, 'Failure'), (9, 'Primary Default')], null=True)),
                ('Days_In_Treatment', models.IntegerField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_month', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6')])),
                ('bacilloscopy_result', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Not Performed')], null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_visits', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='treatments.treatment')),
            ],
            options={
                'ordering': ['visit_month'],
                'unique_together': {('patient', 'visit_month')},
            },
        ),
    ]
