# Generated by Django 4.2.10 on 2026-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringvisit',
            name='adverse_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringvisit',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringvisit',
            name='symptoms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitoringvisit',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
