# Generated by Django 4.2.10 on 2026-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
