# Generated by Django 6.0.3 on 2026-03-09 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Patient', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Notification_Date', models.DateField(blank=True, null=True)),
                ('Sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (9, 'Ignored')], null=True)),
                ('Race', models.IntegerField(blank=True, choices=[(1, 'White'), (2, 'Black'), (3, 'Yellow'), (4, 'Brown'), (5, 'Indigenous'), (9, 'Ignored')], null=True)),
                ('Treatment', models.IntegerField(blank=True, choices=[(1, 'New Case'), (2, 'Relapse'), (3, 'Re-entry'), (4, "Don't Know"), (5, 'Transfer'), (6, 'Post-mortem'), (9, 'Ignored')], null=True)),
                ('Chest_X_Ray', models.IntegerField(blank=True, choices=[(1, 'Suspect'), (2, 'Normal'), (3, 'Other Pathology'), (4, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Tuberculin_Test', models.IntegerField(blank=True, choices=[(1, 'Reactor'), (2, 'Non-Reactor'), (3, 'Not Performed'), (4, 'Not Evaluated')], null=True)),
                ('Clinical_Form', models.IntegerField(blank=True, choices=[(1, 'Pulmonary'), (2, 'Extrapulmonary'), (3, 'Pulmonary+Extrapulmonary'), (9, 'Ignored')], null=True)),
                ('AIDS_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Alcoholism_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Diabetes_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Mental_Disorder_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Other_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Drug_Addiction_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('Smoking_Comorbidity', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('HIV', models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative'), (3, 'In Progress'), (4, 'Not Performed'), (9, 'Ignored')], null=True)),
                ('Occupational_Disease', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (9, 'Ignored')], null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
