# Generated by Django 4.2.10 on 2026-04-02 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_clinician',
            field=models.ForeignKey(limit_choices_to={'role': 'CLINICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Lost', 'Lost to Follow-up')], default='Active', max_length=20),
        ),
    ]
